### ISSUE TITLE
[meta] move config files to XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by aliou** [aliou/dotfiles#21]
- [ ] Link most files to `$XDG_CONFIG_HOME`.
- [ ] Create `config` command to quickly edit a config file.
  - [ ] Completions + FZF if no argument is passed

**Comment by aliou** [comment]
Not enough stuff get their configuration from `~/.config`.
